# Generated by Django 3.1.14 on 2022-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
